/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"

long *
bin_date_1_svc(struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */
	long time();
	printf("before time\n");
	result=time((long*)0);
	printf("after time\n");
	return &result;
}

char **
str_date_1_svc(long arg1,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	char *ctime();
	printf("before ctime\n");
	result = ctime(&arg1);
	printf("after ctime\n");
	return &result;
}
