all: forktest forktest2 forktest3 forktest4 hello

forktest: forktest.c
	gcc -o forktest forktest.c

forktest2: forktest2.c
	gcc -o forktest2 forktest2.c

forktest3: forktest3.c
	gcc -o forktest3 forktest3.c

forktest4: forktest4.c
	gcc -o forktest4 forktest4.c

hello: hello.c
	gcc -o hello hello.c
