SELECT b.TITLE, p.NAME, p.PHONE
	FROM BOOKS b, PUBLISHER p
	WHERE b.PUBID = p.PUBID;
	
SELECT b.TITLE, p.NAME, p.PHONE
	FROM BOOKS b JOIN PUBLISHER p
	ON b.PUBID = p.PUBID;
	
SELECT c.LASTNAME, o.ORDERDATE
	FROM CUSTOMERS c, ORDERS o
	WHERE SHIPDATE IS NULL
	AND c.CUSTOMER# = o.CUSTOMER#;
	
SELECT c.LASTNAME, o.ORDERDATE
	FROM CUSTOMERS c JOIN ORDERS o
	ON SHIPDATE IS NULL
	AND c.CUSTOMER# = o.CUSTOMER#;
	
SELECT DISTINCT b.TITLE, c.FIRSTNAME || ' ' || c.LASTNAME AS "Name" 
	FROM CUSTOMERS c, ORDERS o, ORDERITEMS oi, BOOKS b
	WHERE (c.FIRSTNAME = 'JAKE' AND c.LASTNAME = 'LUCAS') AND c.CUSTOMER# = o.CUSTOMER# AND o.ORDER# = oi.ORDER# AND oi.ISBN = b.ISBN;
	
SELECT DISTINCT b.TITLE, c.FIRSTNAME || ' ' || c.LASTNAME AS "Name"
	FROM CUSTOMERS c JOIN ORDERS o USING (CUSTOMER#)
		JOIN ORDERITEMS oi USING (ORDER#)
		JOIN BOOKS b USING (ISBN)
	WHERE (c.FIRSTNAME = 'JAKE' AND c.LASTNAME = 'LUCAS');
	
SELECT c.FIRSTNAME || ' ' || c.LASTNAME AS "Name", (oi.PAIDEACH) AS "Customer Payment", b.TITLE, o.ORDERDATE
	FROM CUSTOMERS c, ORDERS o, ORDERITEMS oi, BOOKS b
	WHERE c.CUSTOMER# = o.CUSTOMER# AND o.ORDER# = oi.ORDER# AND oi.ISBN = b.ISBN AND (c.FIRSTNAME = 'JAKE' AND c.LASTNAME = 'LUCAS')
	ORDER BY o.ORDERDATE, (RETAIL - DISCOUNT - COST) DESC;
	
SELECT c.FIRSTNAME || ' ' || c.LASTNAME AS "Name", (oi.PAIDEACH) AS "Customer Payment", b.TITLE, o.ORDERDATE
	FROM CUSTOMERS c JOIN ORDERS o USING (CUSTOMER#)
		JOIN ORDERITEMS oi USING (ORDER#)
		JOIN BOOKS b USING (ISBN)
	WHERE (c.FIRSTNAME = 'JAKE' AND c.LASTNAME = 'LUCAS')
	ORDER BY o.ORDERDATE, (RETAIL - DISCOUNT - COST) DESC;

SELECT c.FIRSTNAME || ' ' || c.LASTNAME AS "Name", a.FNAME || ' ' || a.LNAME AS "Author Name"
	FROM CUSTOMERS c, ORDERS o, ORDERITEMS oi, BOOKAUTHOR ba, AUTHOR a
	WHERE c.CUSTOMER# = o.CUSTOMER# AND o.ORDER# = oi.ORDER# AND oi.ISBN = ba.ISBN AND ba.AUTHORID = a.AUTHORID AND c.FIRSTNAME = 'BECCA' AND c.LASTNAME = 'NELSON';
	
SELECT c.FIRSTNAME || ' ' || c.LASTNAME AS "Name", a.FNAME || ' ' || a.LNAME AS "Author Name"
	FROM CUSTOMERS c JOIN ORDERS o USING (CUSTOMER#)
		JOIN ORDERITEMS oi USING (ORDER#)
		JOIN BOOKAUTHOR ba USING (ISBN)
		JOIN AUTHOR a USING (AUTHORID)
	WHERE (c.FIRSTNAME = 'BECCA' AND c.LASTNAME = 'NELSON');


/*Chapter 11*/

SELECT COUNT(CATEGORY) AS "Total # of books in COOKING:"
	FROM BOOKS
	WHERE CATEGORY = 'COOKING';;

SELECT CUSTOMER#, SUM((oi.PAIDEACH-b.COST)*oi.QUANTITY) AS "Total Profit"
	FROM CUSTOMERS c JOIN ORDERS o USING (CUSTOMER#)
		JOIN ORDERITEMS oi USING (ORDER#)
		JOIN BOOKS b USING (ISBN)
	WHERE CUSTOMER# = 1017
	GROUP BY CUSTOMER#;

SELECT MIN(RETAIL)
	FROM BOOKS
	WHERE CATEGORY = 'COMPUTER';
	
SELECT AVG((oi.PAIDEACH-b.COST)*oi.QUANTITY) AS "Average Profit in ORDERS"
	FROM ORDERITEMS oi, BOOKS b, ORDERS o
	WHERE oi.ORDER# = o.ORDER# AND b.ISBN = oi.ISBN;

SELECT COUNT(SHIPDATE)
	FROM ORDERS
	WHERE SHIPDATE IS NOT NULL;

SELECT AVG(RETAIL), p.NAME, CATEGORY
	FROM BOOKS b, PUBLISHER p
	WHERE (b.PUBID = p.PUBID) AND (CATEGORY = 'CHILDREN' OR CATEGORY = 'COMPUTER')
	GROUP BY NAME, CATEGORY
	HAVING AVG(RETAIL) > 50;

SELECT c.FIRSTNAME || ' ' || c.LASTNAME AS "Name", c.STATE, SUM(QUANTITY * PAIDEACH) AS "Order Total"
	FROM CUSTOMERS c, ORDERS o, ORDERITEMS oi
	WHERE (c.CUSTOMER# = o.CUSTOMER#) AND (o.ORDER# = oi.ORDER#) AND 
      (STATE = 'GA' OR STATE = 'FL')
	GROUP BY c.FIRSTNAME, c.LASTNAME, c.STATE
	HAVING SUM(QUANTITY * PAIDEACH) > 80;