/*JLDB_BUILD_5.SQL*/
SELECT *
	FROM BOOKS;
	
SELECT CONTACT AS "CONTACT PERSON", PHONE
	FROM PUBLISHER;
	
SELECT DISTINCT CUSTOMER#
	FROM ORDERS
	ORDER BY CUSTOMER# ASC;

/*Advanced challenge*/
SELECT LASTNAME||','||FIRSTNAME AS "Name", CITY||','||STATE AS "Location", ZIP
	FROM CUSTOMERS;

SELECT TITLE,((RETAIL-COST)/COST)*100 AS "PROFIT%"
FROM BOOKS;
	
/*JLDB_BUILD_8.SQL*/
SELECT TITLE, CATEGORY
  FROM BOOKS
  WHERE CATEGORY != 'FITNESS';
	
SELECT CUSTOMER#, LASTNAME, STATE
	FROM CUSTOMERS
	WHERE (STATE = 'GA' OR STATE = 'NJ')
	ORDER BY LASTNAME;
	
SELECT CUSTOMER#, LASTNAME, STATE
	FROM CUSTOMERS
	WHERE STATE IN('GA','NJ')
	ORDER BY LASTNAME;
	
SELECT LASTNAME, REFERRED AS "Referred Customer ID"
	FROM CUSTOMERS
	WHERE REFERRED IS NOT NULL;

SELECT TITLE
	FROM BOOKS
	WHERE TITLE LIKE '_A_N%';
	
SELECT TITLE, PUBDATE
	FROM BOOKS
	WHERE (PUBDATE > '31-DEC-04' AND PUBDATE < '01-JAN-06');
	
SELECT TITLE, PUBDATE
	FROM BOOKS
	WHERE PUBDATE BETWEEN '31-DEC-04' AND '01-JAN-06';	
	
SELECT TITLE, PUBDATE
	FROM BOOKS
	WHERE PUBDATE LIKE '_______05';		
	
/*ADVANCED CHALLENGE*/

SELECT TITLE, (RETAIL-COST) AS "Profit"
	FROM BOOKS
	WHERE (RETAIL-COST) > 10
	ORDER BY (RETAIL-COST) DESC;
	
SELECT TITLE, CATEGORY, PUBID, RETAIL
	FROM BOOKS
	WHERE ((CATEGORY = 'COMPUTER' OR CATEGORY = 'FAMILY LIFE') AND (PUBID = 1 OR PUBID = 3) AND (RETAIL >= 45));