/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cf.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
cfs_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		cfs_pathname cfs_read_1_arg;
		cfs_write_arg cfs_write_1_arg;
		cfs_pathname cfs_mkdir_1_arg;
		cfs_pathname cfs_mkfile_1_arg;
		cfs_pathname cfs_delete_1_arg;
		cfs_pathname cfs_readdir_1_arg;
	} argument;
	union {
		cfs_read_res cfs_read_1_res;
		cfs_error cfs_write_1_res;
		cfs_error cfs_mkdir_1_res;
		cfs_error cfs_mkfile_1_res;
		cfs_error cfs_delete_1_res;
		cfs_readdir_res cfs_readdir_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case CFS_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_null_1_svc;
		break;

	case CFS_READ:
		_xdr_argument = (xdrproc_t) xdr_cfs_pathname;
		_xdr_result = (xdrproc_t) xdr_cfs_read_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_read_1_svc;
		break;

	case CFS_WRITE:
		_xdr_argument = (xdrproc_t) xdr_cfs_write_arg;
		_xdr_result = (xdrproc_t) xdr_cfs_error;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_write_1_svc;
		break;

	case CFS_MKDIR:
		_xdr_argument = (xdrproc_t) xdr_cfs_pathname;
		_xdr_result = (xdrproc_t) xdr_cfs_error;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_mkdir_1_svc;
		break;

	case CFS_MKFILE:
		_xdr_argument = (xdrproc_t) xdr_cfs_pathname;
		_xdr_result = (xdrproc_t) xdr_cfs_error;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_mkfile_1_svc;
		break;

	case CFS_DELETE:
		_xdr_argument = (xdrproc_t) xdr_cfs_pathname;
		_xdr_result = (xdrproc_t) xdr_cfs_error;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_delete_1_svc;
		break;

	case CFS_READDIR:
		_xdr_argument = (xdrproc_t) xdr_cfs_pathname;
		_xdr_result = (xdrproc_t) xdr_cfs_readdir_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))cfs_readdir_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!cfs_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
