/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cf.h"

bool_t
xdr_cfs_pathname (XDR *xdrs, cfs_pathname *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_file_data (XDR *xdrs, cfs_file_data *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->cfs_file_data_val, (u_int *) &objp->cfs_file_data_len, 4096))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_error (XDR *xdrs, cfs_error *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_read_res (XDR *xdrs, cfs_read_res *objp)
{
	register int32_t *buf;

	 if (!xdr_cfs_error (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case CFERR_NONE:
		 if (!xdr_cfs_file_data (xdrs, &objp->cfs_read_res_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_cfs_write_arg (XDR *xdrs, cfs_write_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_cfs_pathname (xdrs, &objp->pn))
		 return FALSE;
	 if (!xdr_cfs_file_data (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_readdir_res (XDR *xdrs, cfs_readdir_res *objp)
{
	register int32_t *buf;

	 if (!xdr_cfs_error (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case CFERR_NONE:
		 if (!xdr_array (xdrs, (char **)&objp->cfs_readdir_res_u.ents.ents_val, (u_int *) &objp->cfs_readdir_res_u.ents.ents_len, ~0,
			sizeof (cfs_pathname), (xdrproc_t) xdr_cfs_pathname))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
