/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SolveMaze */

#ifndef _Included_SolveMaze
#define _Included_SolveMaze
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SolveMaze
 * Method:    findpath
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_SolveMaze_findpath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
